#!/bin/sh
# build_single_file.sh — inline styles.css and every js/*.js referenced by
# index.html into dist/index.html so the app runs as ONE file from file://.
# Also regenerates js/schema.js from notes.schema.json first.
set -e
cd "$(dirname "$0")"
python3 tools/sync_schema.py >/dev/null
mkdir -p dist
python3 - <<'PY'
import re, os, html
src = open('index.html', encoding='utf-8').read()
def inline_css(m):
    css = open(m.group(1), encoding='utf-8').read()
    return '<style>\n' + css + '\n</style>'
def inline_js(m):
    js = open(m.group(1), encoding='utf-8').read()
    # "</script>" inside JS source would end the tag early; split it defensively
    js = js.replace('</script', '<\\/script')
    return '<script>\n' + js + '\n</script>'
out = re.sub(r'<link rel="stylesheet" href="([^"]+)">', inline_css, src)
out = re.sub(r'<script src="([^"]+)"></script>', inline_js, out)
out = out.replace('<title>Note</title>', '<title>Note</title>\n<!-- single-file build; generated by build_single_file.sh — edit the sources, not this file -->')
open('dist/index.html', 'w', encoding='utf-8').write(out)
print('wrote dist/index.html (%d KB)' % (len(out.encode()) // 1024))
PY
